swagger: '2.0'
info:
  title: Access Control Point API
  description: Interface where SMS access to RISIS datasets
  version: "1.0"
# will be prefixed to all paths
basePath: /v1.0
# the domain of the service
host: nano.api.risis.eu
# array of all schemes that your API supports
schemes:
  - http
produces:
  - application/json
paths:
  /metadata:
    get:
      summary: Metadata of datasets.
      description: The datasets metadata.
      parameters:
        - name: accessToken
          in: query
          description: Access Token
          required: true
          type: string
      tags:
        - Datasets
      responses:
        200:
          description: An object with metadata about dataset.
          schema:
            $ref: '#/definitions/Metadata'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /entityTypes:
    get:
      summary: List of available entity types.
      description: List of entity types and urls for the current dataset.
      parameters:
        - name: accessToken
          in: query
          description: Access Token
          required: true
          type: string
      tags:
        - Entities
      responses:
        200:
          description: An array of available entities.
          schema:
            type: array
            items:
              $ref: '#/definitions/EntityType'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /entities/{entityType}/{id}:
    get:
      summary: Request data for a specific entity type and id.
      description: Query on entity.
      parameters:
        - name: entityType
          in: path
          description: Type of the entity.
          required: true
          type: string
        - name: id
          in: path
          description: The id.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Access Token
          required: true
          type: string
      tags:
        - Entities
      responses:
        200:
          description: An object of entity properties for a given entity id.
          schema:
            $ref: '#/definitions/Entities'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /entities/{entityType}:
    get:
      summary: Request data for a specific entity type.
      description: Query on entity.
      parameters:
        - name: entityType
          in: path
          description: Type of the entity.
          required: true
          type: string
        - name: offset
          in: query
          description: The id of the first record that will be send.
          required: false
          type: integer
        - name: limit
          in: query
          description: The maximum number of records that will be sent.
          required: false
          type: integer
        - name: accessToken
          in: query
          description: Access Token
          required: true
          type: string
      tags:
        - Entities
      responses:
        200:
          description: An object with multiple entities of a specific given type.
          schema:
            $ref: '#/definitions/Entities'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /entities/{entityType}/count:
    get:
      summary: Number of records for a given entity.
      description: Count the number of records for an entity of the dataset.
      parameters:
        - name: entityType
          in: path
          description: Type of the entity.
          required: true
          type: string
        - name: accessToken
          in: query
          description: Access Token
          required: true
          type: string
      tags:
        - Entities
      responses:
        200:
          description: An object with count information for the current entity type.
          schema:
            $ref: '#/definitions/CountDetails'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  EntityType:
    type: object
    properties:
      name:
        type: string
        description: Unique identifier representing a specific entity.
      path:
        type: string
        description: Url Path where the entity is accessible.
      description:
        type: string
        description: A description of the entity type.
  Metadata:
    type: object
    properties:
      title:
        type: string
        description: The name of the dataset.
      description:
        type: string
        description: A description of the dataset.
      creationDate:
        type: string
        description: The creation date of the dataset.
      contact_person:
        type: string
        description: The name of the person in charge of the dataset who can provide more details on it.
      contact_email:
        type: string
        description: The e-mail of the person in charge of the dataset who can provide more details on it.
      contact_organisation:
        type: string
        description: The organisation of the contact person.
  Entities:
    type: object
    properties:
      dataset:
        type: string
        description: Name of the dataset.
      version:
        type: string
        description: Version of the dataset from which the entity is extracted.
      entity_type:
        type: string
        description: Type of the entity. Must start with a capital letter.
      offset:
        type: integer
        description: The id of the first record that has been sent.
      limit:
        type: integer
        description: The maximum number of records that has been sent.
      property_description:
        type: array
        description: List of properties descriptions.
        items:
          $ref: '#/definitions/PropertyDescription'
      instances:
        type: array
        items:
          $ref: '#/definitions/EntityProperties'
  EntityProperties:
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the entity
      property_values:
        type: array
        items:
          $ref: '#/definitions/EntityValues'
  EntityValues:
    type: object
    properties:
      property:
        type: string
        description: name of the property
      value:
        type: string
        description: value of the property
  PropertyDescription:
    type: object
    properties:
      name:
        type: string
        description: Name of the property.
      description:
        type: string
        description: Description of the property.
      hasEntityType:
        type: string
        description: If the property corresponds to another entity, it specifies the entity type. Must start with a capital letter.
  CountDetails:
    type: object
    properties:
      total:
        type: integer
        description: The number of records for the current entity type.
      max_per_page:
        type: integer
        description: The maximum number of record per page for the current entity type.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
