swagger: '2.0'
info:
  title: Access Control Point API
  description: Interface where SMS access to RISIS datasets
  version: "0.3"
# the domain of the service
host: api.risis.eu
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /datasets:
    get:
      summary: List of available datasets.
      description: |
        List of available datasets and their urls.
      tags:
        - Datasets
      responses:
        200:
          description: An array of object with datasets names and urls.
          schema:
            type: array
            items:
              $ref: '#/definitions/Dataset'
  /datasets/{datasetName}:
    get:
      summary: Metadata of datasets.
      description: |
        The datasets metadata.
      parameters:
        - name: datasetName
          in: path
          description: Dataset name.
          required: true
          type: string
      tags:
        - Datasets
        - Entities
      responses:
        200:
          description: An object with metadata about dataset.
          schema:
            type: object
            items:
              $ref: '#/definitions/Metadata'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /datasets/{datasetName}/entities:
    get:
      summary: List of available entity types.
      description: List of entitt types and urls for the current dataset.
      parameters:
        - name: datasetName
          in: path
          description: Dataset name.
          required: true
          type: string
      tags:
        - Datasets
        - Entities
      responses:
        200:
          description: An array of available entities.
          schema:
            type: array
            items:
              $ref: '#/definitions/Entity'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /datasets/{datasetName}/entities/{entityType}:
    get:
      summary: Request data for a specific entity type.
      description: Query on entity.
      parameters:
        - name: datasetName
          in: path
          description: Dataset name.
          required: true
          type: string
        - name: entityType
          in: path
          description: Type of the entity.
          required: true
          type: string
        - name: offset
          in: query
          description: The id of the first record that will be send.
          required: false
          type: integer
        - name: limit
          in: query
          description: The maximum number of records that will be sens.
          required: false
          type: integer
      tags:
        - Datasets
        - Entities
      responses:
        200:
          description: An object with values, result of the query on entity.
          schema:
            type: object
            items:
              $ref: '#/definitions/Result'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /datasets/{datasetName}/entities/{entityType}/count:
    get:
      summary: Number of records for a given entity.
      description: Count the number of records for an entity of the dataset.
      parameters:
        - name: datasetName
          in: path
          description: Dataset name.
          required: true
          type: string
        - name: entityType
          in: path
          description: Type of the entity.
          required: true
          type: string
      tags:
        - Entities
      responses:
        200:
          description: The number of records for the current entity type.
          schema:
            type: integer
definitions:
  Dataset:
    type: object
    properties:
      name:
        type: string
        description: Unique identifier representing a specific dataset.
      path:
        type: string
        description: Url Path where the dataset is accessible.
  Entity:
    type: object
    properties:
      name:
        type: string
        description: Unique identifier representing a specific entity.
      path:
        type: string
        description: Url Path where the entity is accessible.
  Metadata:
    type: object
    properties:
      name:
        type: string
        description: Unique identifier representing a specific dataset.
  Result:
    type: object
    properties:
      data:
        type: object
        description: The result of the query.
      metadata:
        type: object
        description: Information about the query. To be completed...
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
